import { test, expect } from '../../fixtures/base-test';
import {
  rebuildProjectsJson,
  removeTestPost,
  resetTestPosts,
  TEST_POST_FILENAME,
  writeTestPost,
} from '../../utils/posts';

const INITIAL_TITLE = 'E2E Test Project';
const UPDATED_TITLE = 'E2E Updated Project';
const INITIAL_EXCERPT = 'Generated by Playwright to verify post sync.';
const UPDATED_EXCERPT = 'Updated excerpt after editing the markdown post.';

test.describe('Project posts sync', () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeEach(() => {
    resetTestPosts();
  });

  test.afterAll(() => {
    resetTestPosts();
  });

  test('adding a _posts markdown file shows the project on the page', async ({ page, portfolioPage }) => {
    writeTestPost({ title: INITIAL_TITLE, excerpt: INITIAL_EXCERPT });
    rebuildProjectsJson();

    await page.reload();
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();

    await expect(
      portfolioPage.projectsSection.getByRole('heading', { name: INITIAL_TITLE, level: 5 })
    ).toBeVisible();
    await expect(portfolioPage.projectsSection.getByText(INITIAL_EXCERPT)).toBeVisible();
  });

  test('editing a _posts markdown file updates the rendered project', async ({ page, portfolioPage }) => {
    writeTestPost({ title: INITIAL_TITLE, excerpt: INITIAL_EXCERPT });
    rebuildProjectsJson();

    writeTestPost({
      title: UPDATED_TITLE,
      excerpt: UPDATED_EXCERPT,
      body: 'Updated body content for the edited post.',
    });
    rebuildProjectsJson();

    await page.reload();
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();

    await expect(
      portfolioPage.projectsSection.getByRole('heading', { name: UPDATED_TITLE, level: 5 })
    ).toBeVisible();
    await expect(portfolioPage.projectsSection.getByText(UPDATED_EXCERPT)).toBeVisible();
    await expect(
      portfolioPage.projectsSection.getByRole('heading', { name: INITIAL_TITLE, level: 5 })
    ).toHaveCount(0);
  });

  test('removing a _posts markdown file removes the project from the page', async ({ page, portfolioPage }) => {
    writeTestPost({ title: UPDATED_TITLE, excerpt: UPDATED_EXCERPT });
    rebuildProjectsJson();

    removeTestPost(TEST_POST_FILENAME);
    rebuildProjectsJson();

    await page.reload();
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();

    await expect(
      portfolioPage.projectsSection.getByRole('heading', { name: UPDATED_TITLE, level: 5 })
    ).toHaveCount(0);
    await expect(portfolioPage.projectsSection.getByText(UPDATED_EXCERPT)).toHaveCount(0);
  });
});
