import { test, expect } from '../../fixtures/base-test';
import {
  rebuildProjectsJson,
  removeTestPost,
  writeTestPost,
} from '../../utils/posts';
import { MOBILE_VIEWPORT } from '../../utils/viewport';

// Use a filename distinct from TEST_POST_FILENAME so posts-sync's resetTestPosts()
// cannot delete this post while these tests are running in parallel.
const DETAIL_POST_FILENAME = '2099-12-31-e2e-detail-test-post.md';
const DETAIL_SLUG = '2099-12-31-e2e-detail-test-post';
const DETAIL_TITLE = 'E2E Detail Test Project';
const DETAIL_EXCERPT = 'Generated by Playwright to verify the project detail page.';
const DETAIL_BODY = `## Detail Section\n\nThis is the **body** of the test post with an [example link](https://example.com).\n\n- Item one\n- Item two`;

test.describe('Project detail modal', () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(() => {
    writeTestPost({ title: DETAIL_TITLE, excerpt: DETAIL_EXCERPT, body: DETAIL_BODY, filename: DETAIL_POST_FILENAME });
    rebuildProjectsJson();
  });

  test.afterAll(() => {
    removeTestPost(DETAIL_POST_FILENAME);
    rebuildProjectsJson();
  });

  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  // ── Modal visibility ────────────────────────────────────────────────────

  test('modal is closed on initial page load', async ({ portfolioPage }) => {
    await expect(portfolioPage.projectModal).not.toHaveAttribute('open', '');
  });

  // ── Opening the detail view ───────────────────────────────────────────────

  test('clicking Read more opens the project modal', async ({ portfolioPage }) => {
    await portfolioPage.openFirstBlogPost();

    await expect(portfolioPage.projectModal).toHaveAttribute('open', '');
  });

  test('clicking Read more updates the URL to the project hash', async ({ page, portfolioPage }) => {
    await portfolioPage.openFirstBlogPost();

    await expect(page).toHaveURL(/#projects\//);
  });

  // ── Detail content ────────────────────────────────────────────────────────

  test('modal displays the correct project title', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.projectModalTitle).toHaveText(DETAIL_TITLE);
  });

  test('modal displays the formatted date', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.projectModalMeta).toHaveText('Jan 1, 2099');
  });

  // ── Markdown rendering ────────────────────────────────────────────────────

  test('body renders markdown headings as HTML heading elements', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.projectModalBody.locator('h2')).toHaveText('Detail Section');
  });

  test('body renders markdown bold as <strong> elements', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.projectModalBody.locator('strong')).toHaveText('body');
  });

  test('body renders markdown lists as <li> elements', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.projectModalBody.locator('li')).toHaveCount(2);
  });

  test('body links open in a new tab', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    const link = portfolioPage.projectModalBody.locator('a[href="https://example.com"]');
    await expect(link).toHaveAttribute('target', '_blank');
    await expect(link).toHaveAttribute('rel', 'noopener noreferrer');
  });

  // ── Close button layout ───────────────────────────────────────────────────

  test('close button is positioned in the upper-right of the modal header', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    const position = await page.evaluate(() => {
      const close = document.getElementById('project-modal-close')!;
      const header = document.querySelector('.project-modal-header')!;
      const closeRect = close.getBoundingClientRect();
      const headerRect = header.getBoundingClientRect();
      return {
        closeTop: closeRect.top,
        closeRight: closeRect.right,
        headerTop: headerRect.top,
        headerRight: headerRect.right,
        closeHeight: closeRect.height,
      };
    });

    expect(position.closeTop - position.headerTop).toBeLessThan(5);
    expect(position.headerRight - position.closeRight).toBeLessThan(5);
    expect(position.closeHeight).toBeLessThan(50);
  });

  // ── Closing the modal ─────────────────────────────────────────────────────

  test('close button hides the project modal', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);
    await expect(portfolioPage.projectModal).toHaveAttribute('open', '');

    await portfolioPage.closeProjectModal();

    await expect(portfolioPage.projectModal).not.toHaveAttribute('open', '');
    await expect(page).toHaveURL(/#projects$/);
  });

  test('pressing Escape closes the project modal', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);
    await expect(portfolioPage.projectModal).toHaveAttribute('open', '');

    await page.keyboard.press('Escape');

    await expect(portfolioPage.projectModal).not.toHaveAttribute('open', '');
    await expect(page).toHaveURL(/#projects$/);
  });

  test('browser back button reopens the project modal', async ({ page, portfolioPage }) => {
    await page.goto('/');
    await page.goto(`/#projects/${DETAIL_SLUG}`);
    await expect(portfolioPage.projectModal).toHaveAttribute('open', '');

    await portfolioPage.closeProjectModal();
    await expect(portfolioPage.projectModal).not.toHaveAttribute('open', '');
    await expect(page).toHaveURL(/#projects$/);

    await page.goBack();
    await expect(page).toHaveURL(new RegExp(`#projects/${DETAIL_SLUG}$`));
    await expect(portfolioPage.projectModal).toHaveAttribute('open', '');
  });

  // ── Direct URL navigation ─────────────────────────────────────────────────

  test('navigating directly to a project URL opens the project modal', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.projectModal).toHaveAttribute('open', '');
    await expect(portfolioPage.projectModalTitle).toHaveText(DETAIL_TITLE);
  });

  test('unknown slug falls back gracefully — modal stays closed', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail('does-not-exist');

    await expect(portfolioPage.projectModal).not.toHaveAttribute('open', '');
    await expect(page.locator('#page-wrapper')).toBeVisible();
  });

  // ── Read more button integrity ──────────────────────────────────────────────

  test('Read more button slug matches the data-slug attribute', async ({ portfolioPage }) => {
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();

    const readMoreButtons = portfolioPage.projectsSection.locator('button.project-readmore[data-slug]');
    const count = await readMoreButtons.count();

    for (let i = 0; i < count; i++) {
      const button = readMoreButtons.nth(i);
      const slug = await button.getAttribute('data-slug');
      expect(slug).toBeTruthy();
    }
  });

  test.describe('mobile viewport', () => {
    test.use({ viewport: MOBILE_VIEWPORT });

    test('project modal and close button stay within the mobile viewport', async ({ portfolioPage }) => {
      await portfolioPage.gotoProjectDetail(DETAIL_SLUG);
      await expect(portfolioPage.projectModal).toHaveAttribute('open', '');

      const bounds = await portfolioPage.isModalFullyWithinViewport('project-modal');
      expect(bounds.withinViewport).toBe(true);
      expect(bounds.dialog.bottom).toBeLessThanOrEqual(bounds.viewport.height + 1);
      expect(bounds.dialog.right).toBeLessThanOrEqual(bounds.viewport.width + 1);
      expect(bounds.close).not.toBeNull();
      expect(bounds.close!.right).toBeLessThanOrEqual(bounds.viewport.width + 1);
      expect(bounds.close!.top).toBeGreaterThanOrEqual(-1);
    });
  });
});
