import { test, expect } from '../../fixtures/base-test';
import {
  rebuildProjectsJson,
  removeTestPost,
  writeTestPost,
} from '../../utils/posts';

// Use a filename distinct from TEST_POST_FILENAME so posts-sync's resetTestPosts()
// cannot delete this post while these tests are running in parallel.
const DETAIL_POST_FILENAME = '2099-12-31-e2e-detail-test-post.md';
const DETAIL_SLUG = '2099-12-31-e2e-detail-test-post';
const DETAIL_TITLE = 'E2E Detail Test Project';
const DETAIL_EXCERPT = 'Generated by Playwright to verify the project detail page.';
const DETAIL_BODY = `## Detail Section\n\nThis is the **body** of the test post.\n\n- Item one\n- Item two`;

test.describe('Project detail page', () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(() => {
    writeTestPost({ title: DETAIL_TITLE, excerpt: DETAIL_EXCERPT, body: DETAIL_BODY, filename: DETAIL_POST_FILENAME });
    rebuildProjectsJson();
  });

  test.afterAll(() => {
    removeTestPost(DETAIL_POST_FILENAME);
    rebuildProjectsJson();
  });

  test.beforeEach(async ({ page }) => {
    await page.reload();
  });

  // ── Overlay visibility ────────────────────────────────────────────────────

  test('detail overlay is hidden on initial page load', async ({ portfolioPage }) => {
    await expect(portfolioPage.detailOverlay).toBeHidden();
  });

  // ── Opening the detail view ───────────────────────────────────────────────

  test('clicking Read more shows the detail overlay', async ({ page, portfolioPage }) => {
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();
    await portfolioPage.projectsSection.getByRole('link', { name: 'Read more' }).first().click();

    await expect(portfolioPage.detailOverlay).toBeVisible();
  });

  test('clicking Read more updates the URL to the project hash', async ({ page, portfolioPage }) => {
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();
    await portfolioPage.projectsSection.getByRole('link', { name: 'Read more' }).first().click();

    await expect(page).toHaveURL(/#projects\//);
  });

  // ── Detail content ────────────────────────────────────────────────────────

  test('detail page displays the correct project title', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailTitle).toHaveText(DETAIL_TITLE);
  });

  test('detail page displays the formatted date', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailDate).toHaveText('Jan 1, 2099');
  });

  test('detail page displays all project tags', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailTags).toContainText('E2E');
    await expect(portfolioPage.detailTags).toContainText('Testing');
  });

  // ── Markdown rendering ────────────────────────────────────────────────────

  test('body renders markdown headings as HTML heading elements', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailBody.locator('h2')).toHaveText('Detail Section');
  });

  test('body renders markdown bold as <strong> elements', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailBody.locator('strong')).toHaveText('body');
  });

  test('body renders markdown lists as <li> elements', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailBody.locator('li')).toHaveCount(2);
  });

  // ── Back navigation ───────────────────────────────────────────────────────

  test('Back to Projects button hides the detail overlay', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);
    await expect(portfolioPage.detailOverlay).toBeVisible();

    await portfolioPage.detailBackBtn.click();

    await expect(portfolioPage.detailOverlay).toBeHidden();
  });

  test('Back to Projects button navigates to the #projects section', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);
    await portfolioPage.detailBackBtn.click();

    await expect(page).toHaveURL(/#projects$/);
  });

  test('browser back button reopens the detail overlay', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);
    await portfolioPage.detailBackBtn.click();
    await expect(portfolioPage.detailOverlay).toBeHidden();

    await page.goBack();

    await expect(portfolioPage.detailOverlay).toBeVisible();
  });

  // ── Direct URL navigation ─────────────────────────────────────────────────

  test('navigating directly to a project URL shows the detail overlay', async ({ portfolioPage }) => {
    await portfolioPage.gotoProjectDetail(DETAIL_SLUG);

    await expect(portfolioPage.detailOverlay).toBeVisible();
    await expect(portfolioPage.detailTitle).toHaveText(DETAIL_TITLE);
  });

  test('unknown slug falls back gracefully — detail stays hidden', async ({ page, portfolioPage }) => {
    await portfolioPage.gotoProjectDetail('does-not-exist');

    await expect(portfolioPage.detailOverlay).toBeHidden();
    await expect(page.locator('#page-wrapper')).toBeVisible();
  });

  // ── Read more link integrity ──────────────────────────────────────────────

  test('Read more link slug matches the data-slug attribute', async ({ portfolioPage }) => {
    await portfolioPage.projectsSection.scrollIntoViewIfNeeded();

    const readMoreLinks = portfolioPage.projectsSection.locator('.project-readmore');
    const count = await readMoreLinks.count();

    for (let i = 0; i < count; i++) {
      const link = readMoreLinks.nth(i);
      const href = await link.getAttribute('href');
      const slug = await link.getAttribute('data-slug');
      expect(href).toBe(`#projects/${slug}`);
    }
  });
});
